#!/bin/bash

sudo apt update
sudo apt full-upgrade

sudo apt install linux-headers-amd64
sudo apt install nvidia-driver firmware-misc-nonfree

sudo rm /etc/modprobe.d/blacklist-nouveau.conf
sudo touch /etc/modprobe.d/blacklist-nouveau.conf
sudo echo -e "blacklist nouveau\noptions nouveau modeset=0" > /etc/modprobe.d/blacklist-nouveau.conf
sudo update-initramfs -u

sudo reboot
