#!/bin/bash

sudo apt update && sudo apt full-upgrade

cd ../resources/deb-parts
echo -e "$(ls)"
sudo dpkg-split -j sdkmanager.*.deb
echo -e "$(ls)"
sudo apt install -y ./sdkmanager_1.8.1-10392_amd64.deb
echo -e "$(ls)"
sudo rm sdkmanager_1.8.1-10392_amd64.deb

