#!/bin/bash

wget https://downloads.slack-edge.com/releases/linux/4.27.156/prod/x64/slack-desktop-4.27.156-amd64.deb
sudo apt install -y ./slack-desktop-4.27.156-amd64.deb
rm ./slack-desktop-4.27.156-amd64.deb
