#!/bin/bash

echo -e "$(lsblk)\n\n"

echo "------------------------------------------------------------"
echo "Choose a device to freeze: "
echo "------------------------------------------------------------"
tput cuu1 && tput cuu1 && tput cuf 27
read device
echo "------------------------------------------------------------"


echo "------------------------------------------------------------"
echo "Name the output frozen image: "
echo "------------------------------------------------------------"
tput cuu1 && tput cuu1 && tput cuf 30
read name
echo "------------------------------------------------------------"


echo -e "\n\n------------------------------------------------------------"
echo -e "Are you sure you want to freeze ${device} to ~/frozen/${name} ?"
echo -e "(y/n): "
echo -e "------------------------------------------------------------"
tput cuu1 && tput cuu1 && tput cuf 8


old_stty_cfg=$(stty -g)
stty raw -echo
answer=$( while ! head -c 1 | grep -i '[ny]' ;do true ;done )
stty $old_stty_cfg
if echo "$answer" | grep -iq "^y" ;then
    echo -e "Yes, sir"
    echo -e "------------------------------------------------------------"
    sudo dd if=/dev/${device} | gzip>~/frozen/${name}.img.gz status=progress
else
    echo -e "No, please cancel this RIGHT NOW"
    echo -e "------------------------------------------------------------"
fi


